learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    #home page
    path('', views.index, name='index'),

    #show all pizzas
    path('pizza_list', views.pizza_list, name='pizza_list'),

    #toppings for each pizza
    path('pizza_list/<int:pizza_id>/', views.pizza, name='pizza'),

    path('new_pizza/', views.new_pizza, name='new_pizza'),

    path('new_comment/<int:pizza_id>/', views.new_comment, name='new_comment'),

    path('new_topping/<int:pizza_id>/', views.new_topping, name='new_topping'),
]

pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    text = models.CharField(max_length=30)

    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    top_choices = (
        ('B', 'Bacon'),
        ('S', 'Sausage'),
        ('P', 'Pepperoni'),
        ('PN', 'Pineapple'),
        ('SP', 'Spinach'),
        ('M', 'Mushrooms'),
        ('C', 'Chicken'),
        ('A', 'Anchovies'),
        ('GP', 'Green Peppers'),
        ('RP', 'Red Peppers'),
    )
    #text = models.TextField()
    top_choice = models.CharField(max_length=2, choices=top_choices)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'
        
    

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
      
        verbose_name_plural = 'comments'
        
    def __str__(self):
        return f"{self.text[:50]}..."

pizzas/forms.py
from django import forms 
from .models import Pizza, Comment, Topping

class addPizza(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['text']
        labels = {'text': 'Pizza:'}

class addComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Comment:'}

        widgets = {'text': forms.Textarea(attrs={'cols':80})}

class addTopping(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['top_choice']
        labels = {'top_choice': 'Topping:'}

        

pizzas/views.py
from django.shortcuts import render, redirect
from .forms import addPizza, addComment, addTopping
from .models import Pizza

# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')

def pizza_list(request):
   
    pizza_list = Pizza.objects.order_by('date_added')

    context = {'pizza_list':pizza_list}

    return render(request, 'pizzas/pizza_list.html', context)

def pizza(request, pizza_id):

    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza':pizza, 'toppings':toppings}

    return render(request, 'pizzas/pizza.html',context)

def new_pizza(request):
    if request.method != 'POST':
        form = addPizza()
    else:
        form = addPizza(data=request.POST)

        if form.is_valid():
            form.save()
            return redirect('pizzas:pizza_list')

    context = {'form':form}
    return render(request, 'pizzas/new_pizza.html', context)


def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = addComment()
    else:
        form = addComment(data=request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.pizza = pizza
            comment.save()
            form.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'form':form, 'pizza': pizza}
    return render(request, 'pizzas/new_comment.html', context)

def new_topping(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = addTopping()
    else:
        form = addTopping(data=request.POST)

        if form.is_valid():
            top = form.save(commit=False)
            top.pizza = pizza
            top.save()
            form.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'form':form, 'pizza': pizza}
    return render(request, 'pizzas/new_topping.html', context)

pizzas/templates/pizzas/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<HTML>

    <HEAD><TITLE>Mike's Pizzeria</TITLE></HEAD>
    <style>
        h1{font-size:64px;}
h2{font-size:48px;}
h3{font-size:36px;}
h4{font-size:24px;}
h5{font-size:20px;}
h6{font-size:18px;}
    </style>
    <body>
        <div>
            <center><img src="{% static 'images/mikes_pizza.jpg' %}" ALIGN="bottom"> </center>
            <h1 style="text-align:center; color:white;"><a href="{% url 'pizzas:index' %}">Home</a></h1>
            <h2 style="text-align:center; color:white;"><a href="{% url 'pizzas:pizza_list' %}">Pizza Menu</a></h2>
        </div>
        <div>
            <div>
                <div>
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
        <div>
            <hr>
            <p>Contact Information:</p>
            <P>Email me at <a href="mailto:mike_scott@baylor.edu">mike_scott@baylor.edu</a></P>
        </div>
    </body>
</HTML>
    
     

pizzas/templates/pizzas/index.html
{%extends "pizzas/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<HTML>
    
    <BODY>
   
    
        
    <H1>Welcome to Mike's Pizza!</H1>
    
    <CENTER><IMG SRC="{% static 'images/restaurant.jpg' %}" ALIGN="BOTTOM" > </CENTER>

    <H2>We have all the Pizzas you want</H2>
    
    
    
    </BODY>
    
    </HTML>
    
     

  {% endblock content%}

pizzas/templates/pizzas/new_comment.html
{%extends "pizzas/base.html" %}

    {% block content %}
    {% load static %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        <p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>
        <p>Add a new Comment</p>

        <form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}

            <button name="submit">Add Comment</button>
        </form>


    {% endblock content %}

pizzas/templates/pizzas/new_pizza.html
{%extends "pizzas/base.html" %}

    {% block content %}
    {% load static %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        <p>Add a new Pizza</p>

        <form action="{% url 'pizzas:new_pizza' %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <table align="center">
                <tr>
                  <td>
                      <button name="submit" style="align-items: center;">
                        Add Pizza</button>
                    </td>
                    </tr>
                    </table>
        </form>


    {% endblock content %}

pizzas/templates/pizzas/new_topping.html
{%extends "pizzas/base.html" %}

    {% block content %}
    {% load static %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        <p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>
        <p>Add A New Topping</p>

        <form action="{% url 'pizzas:new_topping' pizza.id %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}

            <table align="center">
                <tr>
                  <td>
                      <button name="submit" style="align-items: center;">
                        Add Topping</button>
                    </td>
                    </tr>
                    </table>
        </form>


    {% endblock content %}

pizzas/templates/pizzas/pizza.html
{%extends "pizzas/base.html" %}

{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/base.css' %}">
    <h3 style="text-align:center">{{ pizza }} </h3>
    {% if pizza.text == "Neapolitan Pizza" %}
    <center><IMG SRC="{% static 'images/np.jpg' %}" ALIGN="center" style="width:400px;height:400px;"></center>
    {% elif pizza.text == "Chicago Pizza" %}
    <center><IMG SRC="{% static 'images/chicago.jpg' %}" ALIGN="center" style="width:400px;height:400px;"></center>
    {% elif pizza.text == "New York-Style Pizza" %}
    <center><IMG SRC="{% static 'images/newyork.jpg' %}" ALIGN="center" style="width:400px;height:400px;"></center>
    {% elif pizza.text == "St. Louis-Style Pizza" %}
    <center><IMG SRC="{% static 'images/stl.jpg' %}" ALIGN="center" style="width:400px;height:400px;"></center>
    {% elif pizza.text == "Sicilian Pizza" %}
    <center><IMG SRC="{% static 'images/sicil.jpg' %}" ALIGN="center" style="width:400px;height:400px;"></center>
    {% elif pizza.text == "Greek Pizza" %}
    <center><IMG SRC="{% static 'images/greek.jpg' %}" ALIGN="center" style="width:400px;height:400px;"></center>
    {% elif pizza.text == "BBQ Pizza" %}
    <center><IMG SRC="{% static 'images/bbq.jpg' %}" ALIGN="center" style="width:400px;height:400px;"></center>
    {% endif %}

    <table align="center">
        <tr>
          <td>

    <ul class="b">
        <h4 style="font-size: 40px ; font-weight: bolder; color:forestgreen;">
            Toppings:</h4>
        {% for topping in toppings %}
        <li style="font-size: 20px ; font-weight: normal; color:forestgreen;"> 
            {{ topping.get_top_choice_display }}  
            
        </li>
        {% empty %}
            <li style="font-size: 2em ; font-weight: normal; color:forestgreen;">
                There are no toppings for this pizza yet..</li>
        {% endfor %}
    </ul>
    <ul class="b">
        <li>
            <a href="{% url 'pizzas:new_topping' pizza.id %}">
                <img src="{% static 'images/button_add-a-topping.png' %}" width="width" height="height">
            </a>
        </li>
    </ul>



    <ul class="a">
        <h4 style="font-size: 40px ; font-weight: bolder; color: white;">Comments:</h4>
            {% for comment in pizza.comment_set.all %}
            <li> 
                <p style="text-align:center">Date: {{ comment.date_added|date:'M d, Y H:i' }} <br> Comment: {{ comment.text}}<p>
                
            </li>     
            {% empty %}
                <li style="font-size: 1em ; font-weight: bolder; color:white;">There are no comments for this pizza yet..</li>
            {% endfor %}
    </ul>
    <ul class="b">
        <li>
            <a href="{% url 'pizzas:new_comment' pizza.id%}">
                <img src="{% static 'images/button_add-a-comment.png' %}" width="width" height="height">
            </a>
        </li>
        </ul>

        </td>
        </tr>
        </table>

{% endblock content%}

pizzas/templates/pizzas/pizza_list.html
{%extends "pizzas/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
    <center><h3>Pizzas</h3></center>
    <ul class="a">
        {% for pizza in pizza_list %}
        
            <li>
                <a href="{% url 'pizzas:pizza' pizza.id %}" class="piz">
                    {{pizza}}
                </a>
                    
            </li>

        {% empty %}
            <li>There are no pizzas added yet..</li>
        {% endfor %}
    </ul>
    <ul class="b">
        <li>
            <a href="{% url 'pizzas:new_pizza' %}">
                <img src="{% static 'images/button_add-a-pizza.png' %}" width="width" height="height">
            </a>
        </li>
        </ul>
    
{% endblock content%}